### ISSUE TITLE
Customizable Color - Feature Request

### ISSUE THREAD

**Issue by zythetf2** [DeerUwU/loophud#1]
idk really where to ask you this so ill put it here. First off, amazing stuff, the style and aesthetic of this hud is just through the roof.

Custom color is easier said than done, this would require you to make all of your currently orange hud elements black and white, so that they can be colored by a RGB or HEX value, and all the secondary black elements too since they also have a slight hint of orange.

while this isnt entirely necessary for a hud like this i think that range of personalization would bring a lot... itd defiantly make _me_ use it full time, i just wish i could make it purple lol. i fully understand if you ignore this though.

**Comment by DeerUwU** [comment]
the transition inside gradients usually isn't fixed on a single hue, changing it would make the textures appear more flat. on top of that i would have to split many textures into multiple files
