### ISSUE TITLE
Long custom descriptions on classed items (i.e. mercenary) overlap the collection text

### ISSUE THREAD

**Issue by EmilyEmbers** [DeerUwU/loophud#11]
![07-28 - 10h47m21s](https://github.com/user-attachments/assets/f775da92-6dea-4778-beff-4b5e33fae32c)

**Comment by DeerUwU** [comment]
have you made sure this doesn't occur in the default hud? im pretty sure i haven't touched this hud element.

**Comment by EmilyEmbers** [comment]
You are correct, this is my fault. I was *so* sure this was not a problem in default hud... I'll make sure to double-check next time, regardless of how sure I am.

Either way, would this be fixable?

**Comment by DeerUwU** [comment]
probably not
